environments:
    - name: dev
      configs:
        endpoints:
            production:
                url: 'https://dummy.com/v2/'
        deploymentEnvironments:
            - displayOnDevportal: true
              deploymentEnvironment: Default
              deploymentVhost : localhost