environments:
    - name: dev
      configs:
        endpoints:
            production:
                url: 'https://wellness-dev.com'
        deploymentEnvironments:
            - displayOnDevportal: true
              deploymentEnvironment: Default
              deploymentVhost : localhost